[package]
name = "foxtime"
version = "0.1.0"
edition = "2024"
authors = ["binaryfox <binary@foxontheinter.net>"]
license = "MIT"

[dependencies]
actix-web = { version = "*", features = ["rustls-0_23"] }
clap = { version = "*", features = ["derive"] }
lazy_static = "*"
mime = "*"
rustls = "*"
rustls-pemfile = "*"
sha256 = "*"
